# Generated by Django 5.2.6 on 2025-09-28 00:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("clientes", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Mascota",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nombre", models.CharField(max_length=100)),
                (
                    "especie",
                    models.CharField(
                        choices=[
                            ("perro", "Perro"),
                            ("gato", "Gato"),
                            ("ave", "Ave"),
                            ("otro", "Otro"),
                        ],
                        max_length=20,
                    ),
                ),
                ("raza", models.CharField(blank=True, max_length=100, null=True)),
                ("fecha_nacimiento", models.DateField(blank=True, null=True)),
                ("observaciones", models.TextField(blank=True, null=True)),
                (
                    "cliente",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="mascotas",
                        to="clientes.cliente",
                    ),
                ),
            ],
        ),
    ]
